### ISSUE TITLE
Error loading pre-trained model

### ISSUE THREAD

**Issue by FriedaSmith** [Markin-Wang/CLEViT#1]
Hello, when I run `sh scripts/run_gene.sh`, when loading the pre-trained model, the following error occurs:

traceback : Traceback (most recent call last):
    File "/home/image/anaconda3/envs/plant_diseases/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/home/image/plant_disease/CLEViT/main.py", line 94, in main
      load_pretrained(config, model_without_ddp, logger)
    File "/home/image/plant_disease/CLEViT/utils.py", line 206, in load_pretrained
      relative_position_bias_table_current = model.state_dict()[k]
  KeyError: 'layers.2.blocks.6.attn.relative_position_bias_table'

**Comment by Markin-Wang** [comment]
> Hello, when I run `sh scripts/run_gene.sh`, when loading the pre-trained model, the following error occurs:
> 
> traceback : Traceback (most recent call last): File "/home/image/anaconda3/envs/plant_diseases/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 345, in wrapper return f(*args, **kwargs) File "/home/image/plant_disease/CLEViT/main.py", line 94, in main load_pretrained(config, model_without_ddp, logger) File "/home/image/plant_disease/CLEViT/utils.py", line 206, in load_pretrained relative_position_bias_table_current = model.state_dict()[k] KeyError: 'layers.2.blocks.6.attn.relative_position_bias_table'

Hi, thanks for your interest. I guess the problem is the wrong pretrained model. I provide an example of downloading the swin_base pretrained model at 384 resolution in the README file. However, as shown in the script file, our experiments loaded the swin_base model at 224 resolution. I've updated the README, apologies for the confusion.

**Comment by FriedaSmith** [comment]
I am also using the pre trained model of `swin_base_patch4_window7_224_22k`. Because you did not raise the file in the config folder, I commented out line 259 **_update_config_from_file(config, args.cfg)** in config.py.

```
def update_config(config, args):
    # _update_config_from_file(config, args.cfg)

    config.defrost()
    if args.opts:
        config.merge_from_list(args.opts)

    def _check_args(name):
        if hasattr(args, name) and eval(f'args.{name}'):
            return True
        return False
```

The training command is as follows:

```
export tag='gene_sb7_fullb_np2_lr2e-3_mul5_bs12_448_ep200_linear_ee2'
CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345  main.py \
--dataset soybean_gene \
--tag $tag \
--lr 2e-3 \
--model full_b \
--mask \
--swap \
--con \
--margin 1 \
--origin_w 1 \
--swap_w 0.3 \
--con_w 0.5 \
--num_part 2 \
--img_size 448 \
--cfg configs/swin/swin_base_patch4_window7_448.yaml \
--data-path ./datasets \
--batch-size 8 \
--eval-batch-size 8 \
--epochs 200 \
--pretrained ./pretrained_models/swin_base_patch4_window7_224_22k.pth \
```

**Comment by Markin-Wang** [comment]
> It's not a problem with the pretrained model, I am also using `swin_base_patch4_window7_224_22k`. Because you did not provide the file in the **configs** folder, I commented out line 259 **_update_config_from_file(config, args.cfg)** in config.py.
> 
> ```
> def update_config(config, args):
>     # _update_config_from_file(config, args.cfg)
> 
>     config.defrost()
>     if args.opts:
>         config.merge_from_list(args.opts)
> 
>     def _check_args(name):
>         if hasattr(args, name) and eval(f'args.{name}'):
>             return True
>         return False
> ```
> 
> The training command is as follows:
> 
> ```
> export tag='gene_sb7_fullb_np2_lr2e-3_mul5_bs12_448_ep200_linear_ee2'
> CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345  main.py \
> --dataset soybean_gene \
> --tag $tag \
> --lr 2e-3 \
> --model full_b \
> --mask \
> --swap \
> --con \
> --margin 1 \
> --origin_w 1 \
> --swap_w 0.3 \
> --con_w 0.5 \
> --num_part 2 \
> --img_size 448 \
> --cfg configs/swin/swin_base_patch4_window7_448.yaml \
> --data-path ./datasets \
> --batch-size 8 \
> --eval-batch-size 8 \
> --epochs 200 \
> --pretrained ./pretrained_models/swin_base_patch4_window7_224_22k.pth \
> ```

Hi, sorry forgot the config directory, I have uploaded the config directory and it should work now.

**Comment by FriedaSmith** [comment]
Thank you very much. It is now ready to work.

**Comment by FriedaSmith** [comment]
@Markin-Wang  Sorry to bother you again. Another error has occurred.

```
traceback : Traceback (most recent call last):
    File "/home/image006/anaconda3/envs/plant_diseases/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/home/image006/CQP/plant_disease/CLEViT/main.py", line 108, in main
      train_one_epoch(config, model, criterion, data_loader_train, optimizer, epoch, mixup_fn, lr_scheduler,
    File "/home/image006/CQP/plant_disease/CLEViT/main.py", line 151, in train_one_epoch
      imgs = torch.cat(imgs, dim=0)
  RuntimeError: torch.cat(): expected a non-empty list of Tensors

```

**Comment by FriedaSmith** [comment]
Hi, I found that `imgs` is [] through debugging. What is the reason for this?

![data_loader](https://github.com/Markin-Wang/CLEViT/assets/64420430/92ec1320-bd6b-4f38-a4cd-7a20acbeb69c)
![imgs_label](https://github.com/Markin-Wang/CLEViT/assets/64420430/e738938d-9e66-4c16-9205-9acd35b3254c)


> @Markin-Wang Sorry to bother you again. Another error has occurred.
> 
> ```
> traceback : Traceback (most recent call last):
>     File "/home/image/anaconda3/envs/plant_diseases/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
>       return f(*args, **kwargs)
>     File "/home/image/plant_disease/CLEViT/main.py", line 108, in main
>       train_one_epoch(config, model, criterion, data_loader_train, optimizer, epoch, mixup_fn, lr_scheduler,
>     File "/home/image/plant_disease/CLEViT/main.py", line 151, in train_one_epoch
>       imgs = torch.cat(imgs, dim=0)
>   RuntimeError: torch.cat(): expected a non-empty list of Tensors
> ```

**Comment by Markin-Wang** [comment]
> Hi, I found that `imgs` is [] through debugging. What is the reason for this?
> 
> ![data_loader](https://user-images.githubusercontent.com/64420430/254437681-92ec1320-bd6b-4f38-a4cd-7a20acbeb69c.png) ![imgs_label](https://user-images.githubusercontent.com/64420430/254437694-e738938d-9e66-4c16-9205-9acd35b3254c.png)
> 
> > @Markin-Wang Sorry to bother you again. Another error has occurred.
> > ```
> > traceback : Traceback (most recent call last):
> >     File "/home/image/anaconda3/envs/plant_diseases/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
> >       return f(*args, **kwargs)
> >     File "/home/image/plant_disease/CLEViT/main.py", line 108, in main
> >       train_one_epoch(config, model, criterion, data_loader_train, optimizer, epoch, mixup_fn, lr_scheduler,
> >     File "/home/image/plant_disease/CLEViT/main.py", line 151, in train_one_epoch
> >       imgs = torch.cat(imgs, dim=0)
> >   RuntimeError: torch.cat(): expected a non-empty list of Tensors
> > ```

Hi, you need to make sure that all the images are put under the data_root/images directories.

**Comment by FriedaSmith** [comment]
The number of images is correct.

```
data/soybean_gene/images$ ls -l  | grep "^-" | wc -l
23906
```

**Comment by FriedaSmith** [comment]
I set a breakpoint on line 727 of the **data/dataset.py** file and found that I did not jump to this line during debugging.

![soybean_gene](https://github.com/Markin-Wang/CLEViT/assets/64420430/6fd8e83f-5355-47d1-ae3f-4698d27cec0d)

**Comment by Markin-Wang** [comment]
> Hi, I found that `imgs` is [] through debugging. What is the reason for this?
> 
> ![data_loader](https://user-images.githubusercontent.com/64420430/254437681-92ec1320-bd6b-4f38-a4cd-7a20acbeb69c.png) ![imgs_label](https://user-images.githubusercontent.com/64420430/254437694-e738938d-9e66-4c16-9205-9acd35b3254c.png)
> 
> > @Markin-Wang Sorry to bother you again. Another error has occurred.
> > ```
> > traceback : Traceback (most recent call last):
> >     File "/home/image/anaconda3/envs/plant_diseases/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
> >       return f(*args, **kwargs)
> >     File "/home/image/plant_disease/CLEViT/main.py", line 108, in main
> >       train_one_epoch(config, model, criterion, data_loader_train, optimizer, epoch, mixup_fn, lr_scheduler,
> >     File "/home/image/plant_disease/CLEViT/main.py", line 151, in train_one_epoch
> >       imgs = torch.cat(imgs, dim=0)
> >   RuntimeError: torch.cat(): expected a non-empty list of Tensors
> > ```

Hi, just to update that the possible reason could be the typo in the training script for the 'model' hyperparemeter. We found that when we re-organice our code, we change the condition of the if statement (for args.model variable) to select the model) in data/build.py MyTransform class from "full_b" to "full", however in the training scripts, it is still "full_b'. I have changed the relevant training scripts and code, hence it should work now. Please pull again and contact if you still cannot train the model.
