### ISSUE TITLE
How to visualize the attention heat map?

### ISSUE THREAD

**Issue by FriedaSmith** [Markin-Wang/CLEViT#4]
Hi, I appreciate your work very much. Can you open source the attention visualization part of the code?

**Comment by Markin-Wang** [comment]
> Hi, I appreciate your work very much. Can you open source the attention visualization part of the code?

Hi, thank you for your interest to our work. We utilized the [pytorch-grad-cam](https://github.com/jacobgil/pytorch-grad-cam) to visualize the attention map. The source code about the visualization is in the [extract_features.py](https://github.com/Markin-Wang/CLEViT/blob/main/extract_features.py).

**Comment by FriedaSmith** [comment]
Your help was very much appreciated.
